/**
 * UE4GeneratorTester
 * test
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIAllTypes.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI 
{

inline FString ToString(const OpenAPIAllTypes::Enum1Enum& Value)
{
	switch (Value)
	{
	case OpenAPIAllTypes::Enum1Enum::Enumvalue1:
		return TEXT("enumvalue1");
	case OpenAPIAllTypes::Enum1Enum::Enumvalue2:
		return TEXT("enumvalue2");
	case OpenAPIAllTypes::Enum1Enum::Enumvalue3:
		return TEXT("enumvalue3");
	}

	UE_LOG(LogOpenAPI, Error, TEXT("Invalid OpenAPIAllTypes::Enum1Enum Value (%d)"), (int)Value);	
	return TEXT("");
}

inline FString OpenAPIAllTypes::EnumToString(const OpenAPIAllTypes::Enum1Enum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPIAllTypes::Enum1Enum& Value)
{
	static TMap<FString, OpenAPIAllTypes::Enum1Enum> StringToEnum = { 
		{ TEXT("enumvalue1"), OpenAPIAllTypes::Enum1Enum::Enumvalue1 },
		{ TEXT("enumvalue2"), OpenAPIAllTypes::Enum1Enum::Enumvalue2 },
		{ TEXT("enumvalue3"), OpenAPIAllTypes::Enum1Enum::Enumvalue3 }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

inline bool OpenAPIAllTypes::EnumFromString(const FString& EnumAsString, OpenAPIAllTypes::Enum1Enum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline FStringFormatArg ToStringFormatArg(const OpenAPIAllTypes::Enum1Enum& Value)
{
	return FStringFormatArg(ToString(Value));
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPIAllTypes::Enum1Enum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPIAllTypes::Enum1Enum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPIAllTypes::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("notype")); WriteJsonValue(Writer, Notype);
	Writer->WriteIdentifierPrefix(TEXT("int1")); WriteJsonValue(Writer, Int1);
	Writer->WriteIdentifierPrefix(TEXT("int2")); WriteJsonValue(Writer, Int2);
	Writer->WriteIdentifierPrefix(TEXT("int3")); WriteJsonValue(Writer, Int3);
	Writer->WriteIdentifierPrefix(TEXT("number1")); WriteJsonValue(Writer, Number1);
	Writer->WriteIdentifierPrefix(TEXT("number2")); WriteJsonValue(Writer, Number2);
	Writer->WriteIdentifierPrefix(TEXT("number3")); WriteJsonValue(Writer, Number3);
	Writer->WriteIdentifierPrefix(TEXT("string")); WriteJsonValue(Writer, String);
	Writer->WriteIdentifierPrefix(TEXT("string_byte")); WriteJsonValue(Writer, StringByte);
	Writer->WriteIdentifierPrefix(TEXT("boolean")); WriteJsonValue(Writer, Boolean);
	Writer->WriteIdentifierPrefix(TEXT("date")); WriteJsonValue(Writer, Date);
	Writer->WriteIdentifierPrefix(TEXT("date_time")); WriteJsonValue(Writer, DateTime);
	Writer->WriteIdentifierPrefix(TEXT("password")); WriteJsonValue(Writer, Password);
	if (Enum1.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("enum1")); WriteJsonValue(Writer, Enum1.GetValue());	
	}
	if (Enum2.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("enum2")); WriteJsonValue(Writer, Enum2.GetValue());	
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIAllTypes::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("notype"), Notype);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("int1"), Int1);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("int2"), Int2);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("int3"), Int3);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("number1"), Number1);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("number2"), Number2);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("number3"), Number3);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("string"), String);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("string_byte"), StringByte);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("boolean"), Boolean);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("date"), Date);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("date_time"), DateTime);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("password"), Password);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("enum1"), Enum1);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("enum2"), Enum2);

	return ParseSuccess;
}

}
