/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ModelPrefixPetApi.h"

#include "ModelPrefixPetApiOperations.h"
#include "PetstoreModule.h"

#include "HttpModule.h"
#include "Serialization/JsonSerializer.h"

namespace CppNamespace 
{

ModelPrefixPetApi::ModelPrefixPetApi() 
: Url(TEXT("http://petstore.swagger.io/v2"))
{
}

ModelPrefixPetApi::~ModelPrefixPetApi() {}

void ModelPrefixPetApi::SetURL(const FString& InUrl)
{
	Url = InUrl;
}

void ModelPrefixPetApi::AddHeaderParam(const FString& Key, const FString& Value)
{
	AdditionalHeaderParams.Add(Key, Value);
}

void ModelPrefixPetApi::ClearHeaderParams()
{
	AdditionalHeaderParams.Reset();
}

bool ModelPrefixPetApi::IsValid() const
{
	if (Url.IsEmpty())
	{
		UE_LOG(LogPetstore, Error, TEXT("ModelPrefixPetApi: Endpoint Url is not set, request cannot be performed"));
		return false;
	}

	return true;
}

void ModelPrefixPetApi::HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const
{
	InOutResponse.SetHttpResponse(HttpResponse);
	InOutResponse.SetSuccessful(bSucceeded);

	if (bSucceeded && HttpResponse.IsValid())
	{
		InOutResponse.SetHttpResponseCode((EHttpResponseCodes::Type)HttpResponse->GetResponseCode());
		FString ContentType = HttpResponse->GetContentType();
		FString Content;

		if (ContentType.IsEmpty())
		{
			return; // Nothing to parse
		}
		else if (ContentType.StartsWith(TEXT("application/json")) || ContentType.StartsWith("text/json"))
		{
			Content = HttpResponse->GetContentAsString();

			TSharedPtr<FJsonValue> JsonValue;
			auto Reader = TJsonReaderFactory<>::Create(Content);

			if (FJsonSerializer::Deserialize(Reader, JsonValue) && JsonValue.IsValid())
			{
				if (InOutResponse.FromJson(JsonValue))
					return; // Successfully parsed
			}
		}
		else if(ContentType.StartsWith(TEXT("text/plain")))
		{
			Content = HttpResponse->GetContentAsString();
			InOutResponse.SetResponseString(Content);
			return; // Successfully parsed
		}

		// Report the parse error but do not mark the request as unsuccessful. Data could be partial or malformed, but the request succeeded.
		UE_LOG(LogPetstore, Error, TEXT("Failed to deserialize Http response content (type:%s):\n%s"), *ContentType , *Content);
		return;
	}

	// By default, assume we failed to establish connection
	InOutResponse.SetHttpResponseCode(EHttpResponseCodes::RequestTimeout);
}

bool ModelPrefixPetApi::AddPet(const AddPetRequest& Request, const FAddPetDelegate& Delegate /*= FAddPetDelegate()*/) const
{
	if (!IsValid())
		return false;

	FHttpRequestRef HttpRequest = FHttpModule::Get().CreateRequest();
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);
	
	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ModelPrefixPetApi::OnAddPetResponse, Delegate, Request.GetAutoRetryCount());
	return HttpRequest->ProcessRequest();
}

void ModelPrefixPetApi::OnAddPetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FAddPetDelegate Delegate, int AutoRetryCount) const
{
	AddPetResponse Response;
	Response.SetHttpRequest(HttpRequest);

	HandleResponse(HttpResponse, bSucceeded, Response);

	if(!Response.IsSuccessful() && AutoRetryCount > 0)
	{
		HttpRequest->OnProcessRequestComplete().BindRaw(this, &ModelPrefixPetApi::OnAddPetResponse, Delegate, AutoRetryCount - 1);
		Response.AsyncRetry();		
	}
	else
	{
		Delegate.ExecuteIfBound(Response);
	}
}

bool ModelPrefixPetApi::DeletePet(const DeletePetRequest& Request, const FDeletePetDelegate& Delegate /*= FDeletePetDelegate()*/) const
{
	if (!IsValid())
		return false;

	FHttpRequestRef HttpRequest = FHttpModule::Get().CreateRequest();
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);
	
	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ModelPrefixPetApi::OnDeletePetResponse, Delegate, Request.GetAutoRetryCount());
	return HttpRequest->ProcessRequest();
}

void ModelPrefixPetApi::OnDeletePetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FDeletePetDelegate Delegate, int AutoRetryCount) const
{
	DeletePetResponse Response;
	Response.SetHttpRequest(HttpRequest);

	HandleResponse(HttpResponse, bSucceeded, Response);

	if(!Response.IsSuccessful() && AutoRetryCount > 0)
	{
		HttpRequest->OnProcessRequestComplete().BindRaw(this, &ModelPrefixPetApi::OnDeletePetResponse, Delegate, AutoRetryCount - 1);
		Response.AsyncRetry();		
	}
	else
	{
		Delegate.ExecuteIfBound(Response);
	}
}

bool ModelPrefixPetApi::FindPetsByStatus(const FindPetsByStatusRequest& Request, const FFindPetsByStatusDelegate& Delegate /*= FFindPetsByStatusDelegate()*/) const
{
	if (!IsValid())
		return false;

	FHttpRequestRef HttpRequest = FHttpModule::Get().CreateRequest();
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);
	
	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ModelPrefixPetApi::OnFindPetsByStatusResponse, Delegate, Request.GetAutoRetryCount());
	return HttpRequest->ProcessRequest();
}

void ModelPrefixPetApi::OnFindPetsByStatusResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FFindPetsByStatusDelegate Delegate, int AutoRetryCount) const
{
	FindPetsByStatusResponse Response;
	Response.SetHttpRequest(HttpRequest);

	HandleResponse(HttpResponse, bSucceeded, Response);

	if(!Response.IsSuccessful() && AutoRetryCount > 0)
	{
		HttpRequest->OnProcessRequestComplete().BindRaw(this, &ModelPrefixPetApi::OnFindPetsByStatusResponse, Delegate, AutoRetryCount - 1);
		Response.AsyncRetry();		
	}
	else
	{
		Delegate.ExecuteIfBound(Response);
	}
}

bool ModelPrefixPetApi::FindPetsByTags(const FindPetsByTagsRequest& Request, const FFindPetsByTagsDelegate& Delegate /*= FFindPetsByTagsDelegate()*/) const
{
	if (!IsValid())
		return false;

	FHttpRequestRef HttpRequest = FHttpModule::Get().CreateRequest();
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);
	
	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ModelPrefixPetApi::OnFindPetsByTagsResponse, Delegate, Request.GetAutoRetryCount());
	return HttpRequest->ProcessRequest();
}

void ModelPrefixPetApi::OnFindPetsByTagsResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FFindPetsByTagsDelegate Delegate, int AutoRetryCount) const
{
	FindPetsByTagsResponse Response;
	Response.SetHttpRequest(HttpRequest);

	HandleResponse(HttpResponse, bSucceeded, Response);

	if(!Response.IsSuccessful() && AutoRetryCount > 0)
	{
		HttpRequest->OnProcessRequestComplete().BindRaw(this, &ModelPrefixPetApi::OnFindPetsByTagsResponse, Delegate, AutoRetryCount - 1);
		Response.AsyncRetry();		
	}
	else
	{
		Delegate.ExecuteIfBound(Response);
	}
}

bool ModelPrefixPetApi::GetPetById(const GetPetByIdRequest& Request, const FGetPetByIdDelegate& Delegate /*= FGetPetByIdDelegate()*/) const
{
	if (!IsValid())
		return false;

	FHttpRequestRef HttpRequest = FHttpModule::Get().CreateRequest();
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);
	
	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ModelPrefixPetApi::OnGetPetByIdResponse, Delegate, Request.GetAutoRetryCount());
	return HttpRequest->ProcessRequest();
}

void ModelPrefixPetApi::OnGetPetByIdResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetPetByIdDelegate Delegate, int AutoRetryCount) const
{
	GetPetByIdResponse Response;
	Response.SetHttpRequest(HttpRequest);

	HandleResponse(HttpResponse, bSucceeded, Response);

	if(!Response.IsSuccessful() && AutoRetryCount > 0)
	{
		HttpRequest->OnProcessRequestComplete().BindRaw(this, &ModelPrefixPetApi::OnGetPetByIdResponse, Delegate, AutoRetryCount - 1);
		Response.AsyncRetry();		
	}
	else
	{
		Delegate.ExecuteIfBound(Response);
	}
}

bool ModelPrefixPetApi::UpdatePet(const UpdatePetRequest& Request, const FUpdatePetDelegate& Delegate /*= FUpdatePetDelegate()*/) const
{
	if (!IsValid())
		return false;

	FHttpRequestRef HttpRequest = FHttpModule::Get().CreateRequest();
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);
	
	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ModelPrefixPetApi::OnUpdatePetResponse, Delegate, Request.GetAutoRetryCount());
	return HttpRequest->ProcessRequest();
}

void ModelPrefixPetApi::OnUpdatePetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUpdatePetDelegate Delegate, int AutoRetryCount) const
{
	UpdatePetResponse Response;
	Response.SetHttpRequest(HttpRequest);

	HandleResponse(HttpResponse, bSucceeded, Response);

	if(!Response.IsSuccessful() && AutoRetryCount > 0)
	{
		HttpRequest->OnProcessRequestComplete().BindRaw(this, &ModelPrefixPetApi::OnUpdatePetResponse, Delegate, AutoRetryCount - 1);
		Response.AsyncRetry();		
	}
	else
	{
		Delegate.ExecuteIfBound(Response);
	}
}

bool ModelPrefixPetApi::UpdatePetWithForm(const UpdatePetWithFormRequest& Request, const FUpdatePetWithFormDelegate& Delegate /*= FUpdatePetWithFormDelegate()*/) const
{
	if (!IsValid())
		return false;

	FHttpRequestRef HttpRequest = FHttpModule::Get().CreateRequest();
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);
	
	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ModelPrefixPetApi::OnUpdatePetWithFormResponse, Delegate, Request.GetAutoRetryCount());
	return HttpRequest->ProcessRequest();
}

void ModelPrefixPetApi::OnUpdatePetWithFormResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUpdatePetWithFormDelegate Delegate, int AutoRetryCount) const
{
	UpdatePetWithFormResponse Response;
	Response.SetHttpRequest(HttpRequest);

	HandleResponse(HttpResponse, bSucceeded, Response);

	if(!Response.IsSuccessful() && AutoRetryCount > 0)
	{
		HttpRequest->OnProcessRequestComplete().BindRaw(this, &ModelPrefixPetApi::OnUpdatePetWithFormResponse, Delegate, AutoRetryCount - 1);
		Response.AsyncRetry();		
	}
	else
	{
		Delegate.ExecuteIfBound(Response);
	}
}

bool ModelPrefixPetApi::UploadFile(const UploadFileRequest& Request, const FUploadFileDelegate& Delegate /*= FUploadFileDelegate()*/) const
{
	if (!IsValid())
		return false;

	FHttpRequestRef HttpRequest = FHttpModule::Get().CreateRequest();
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);
	
	HttpRequest->OnProcessRequestComplete().BindRaw(this, &ModelPrefixPetApi::OnUploadFileResponse, Delegate, Request.GetAutoRetryCount());
	return HttpRequest->ProcessRequest();
}

void ModelPrefixPetApi::OnUploadFileResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUploadFileDelegate Delegate, int AutoRetryCount) const
{
	UploadFileResponse Response;
	Response.SetHttpRequest(HttpRequest);

	HandleResponse(HttpResponse, bSucceeded, Response);

	if(!Response.IsSuccessful() && AutoRetryCount > 0)
	{
		HttpRequest->OnProcessRequestComplete().BindRaw(this, &ModelPrefixPetApi::OnUploadFileResponse, Delegate, AutoRetryCount - 1);
		Response.AsyncRetry();		
	}
	else
	{
		Delegate.ExecuteIfBound(Response);
	}
}

}
