/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PetstoreModule.h"

IMPLEMENT_MODULE(PetstoreModule, Petstore);
DEFINE_LOG_CATEGORY(LogPetstore);

void PetstoreModule::StartupModule()
{
}

void PetstoreModule::ShutdownModule()
{
}

