swagger: '2.0'
info:
  description: 'test'
  version: 1.0.0
  title: UE4GeneratorTester
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache-2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: petstore.swagger.io
schemes:
  - http
paths:
  /test:
    post:
      summary: Add a new pet to the store
      description: ''
      operationId: addPet
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Pet object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/AllTypes'
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: true
          type: array
          items:
            type: string
            enum:
              - available
              - pending
              - sold
            default: available
          collectionFormat: csv
      responses:
        '405':
          description: Invalid input
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
    put:
      tags:
        - pet
      summary: Update an existing pet
      description: ''
      operationId: updatePet
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Pet object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/AllTypes'
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/api/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  AllTypes:
    required:
      - notype
      - int1
      - int2
      - int3
      - number1
      - number2
      - number3
      - string
      - string_byte
      - string_binary
      - boolean
      - date
      - date_time
      - password
    properties:
      notype:
        default: 123.456
      int1:
        type: integer
        format: int32
        default: 123456
      int2:
        type: integer
        format: int64
        default: 123456
      int3:
        type: integer
        default: 123456
      number1:
        type: number
        format: float
        default: 123.456
      number2:
        type: number
        format: float
        default: 123.456
      number3:
        type: number
        default: 123.456
      string:
        type: string
        default: toto titi
      string_byte:
        type: string
        format: byte
      boolean:
        type: boolean
        default: true
      date:
        type: string
        format: date
        default: true
      date_time:
        type: string
        format: date-time
        default: true
      password:
        type: string
        format: password
        default: true
      enum1:
        type: string
        default: enumvalue3
        enum:
          - enumvalue1
          - enumvalue2
          - enumvalue3
      enum2:
        type: integer
        default: enumvalue3
        enum:
          - enumvalue1
          - enumvalue2
          - enumvalue3
  StringTypedef:
    type: string
    pattern: '^[A-Z]{3,3}$'
    description: >
      some description
