/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#pragma once

#include "ModelPrefixBaseModel.h"
#include "ModelPrefixPetApi.h"

#include "ModelPrefixHelpers.h"
#include "ModelPrefixApiResponse.h"
#include "ModelPrefixPet.h"

namespace CppNamespace 
{
/* Add a new pet to the store
 *
 * 
*/
class PETSTORE_API ModelPrefixPetApi::AddPetRequest : public Request
{
public:
    virtual ~AddPetRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* Pet object that needs to be added to the store */
	ModelPrefixPet Body;
};

class PETSTORE_API ModelPrefixPetApi::AddPetResponse : public Response
{
public:
    virtual ~AddPetResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    
};

/* Deletes a pet
 *
 * 
*/
class PETSTORE_API ModelPrefixPetApi::DeletePetRequest : public Request
{
public:
    virtual ~DeletePetRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* Pet id to delete */
	int64 PetId;
TOptional<FString> ApiKey;
};

class PETSTORE_API ModelPrefixPetApi::DeletePetResponse : public Response
{
public:
    virtual ~DeletePetResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    
};

/* Finds Pets by status
 *
 * Multiple status values can be provided with comma separated strings
*/
class PETSTORE_API ModelPrefixPetApi::FindPetsByStatusRequest : public Request
{
public:
    virtual ~FindPetsByStatusRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* Status values that need to be considered for filter */
	TArray<FString> Status;
};

class PETSTORE_API ModelPrefixPetApi::FindPetsByStatusResponse : public Response
{
public:
    virtual ~FindPetsByStatusResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    TArray<ModelPrefixPet> Content;
};

/* Finds Pets by tags
 *
 * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
*/
class PETSTORE_API ModelPrefixPetApi::FindPetsByTagsRequest : public Request
{
public:
    virtual ~FindPetsByTagsRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* Tags to filter by */
	TArray<FString> Tags;
};

class PETSTORE_API ModelPrefixPetApi::FindPetsByTagsResponse : public Response
{
public:
    virtual ~FindPetsByTagsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    TArray<ModelPrefixPet> Content;
};

/* Find pet by ID
 *
 * Returns a single pet
*/
class PETSTORE_API ModelPrefixPetApi::GetPetByIdRequest : public Request
{
public:
    virtual ~GetPetByIdRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* ID of pet to return */
	int64 PetId;
};

class PETSTORE_API ModelPrefixPetApi::GetPetByIdResponse : public Response
{
public:
    virtual ~GetPetByIdResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    ModelPrefixPet Content;
};

/* Update an existing pet
 *
 * 
*/
class PETSTORE_API ModelPrefixPetApi::UpdatePetRequest : public Request
{
public:
    virtual ~UpdatePetRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* Pet object that needs to be added to the store */
	ModelPrefixPet Body;
};

class PETSTORE_API ModelPrefixPetApi::UpdatePetResponse : public Response
{
public:
    virtual ~UpdatePetResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    
};

/* Updates a pet in the store with form data
 *
 * 
*/
class PETSTORE_API ModelPrefixPetApi::UpdatePetWithFormRequest : public Request
{
public:
    virtual ~UpdatePetWithFormRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* ID of pet that needs to be updated */
	int64 PetId;
/* Updated name of the pet */
	TOptional<FString> Name;
/* Updated status of the pet */
	TOptional<FString> Status;
};

class PETSTORE_API ModelPrefixPetApi::UpdatePetWithFormResponse : public Response
{
public:
    virtual ~UpdatePetWithFormResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    
};

/* uploads an image
 *
 * 
*/
class PETSTORE_API ModelPrefixPetApi::UploadFileRequest : public Request
{
public:
    virtual ~UploadFileRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* ID of pet to update */
	int64 PetId;
/* Additional data to pass to server */
	TOptional<FString> AdditionalMetadata;
/* file to upload */
	TOptional<HttpFileInput> File;
};

class PETSTORE_API ModelPrefixPetApi::UploadFileResponse : public Response
{
public:
    virtual ~UploadFileResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    ModelPrefixApiResponse Content;
};

}
