/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "ModelPrefixPet.h"

#include "Templates/SharedPointer.h"

namespace CppNamespace 
{

	void ModelPrefixPet::WriteJson(JsonWriter& Writer) const
	{
		Writer->WriteObjectStart();
		if (Id.IsSet())
		{
			Writer->WriteIdentifierPrefix(TEXT("id")); WriteJsonValue(Writer, Id.GetValue());	
		}
		if (Category.IsSet())
		{
			Writer->WriteIdentifierPrefix(TEXT("category")); WriteJsonValue(Writer, Category.GetValue());	
		}
		Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name);
		Writer->WriteIdentifierPrefix(TEXT("photoUrls")); WriteJsonValue(Writer, PhotoUrls);
		if (Tags.IsSet())
		{
			Writer->WriteIdentifierPrefix(TEXT("tags")); WriteJsonValue(Writer, Tags.GetValue());	
		}
		if (Status.IsSet())
		{
			Writer->WriteIdentifierPrefix(TEXT("status")); WriteJsonValue(Writer, Status.GetValue());	
		}
		Writer->WriteObjectEnd();
	}

	bool ModelPrefixPet::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
	{
		bool ParseSuccess = true;

		ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("id"), Id);
		ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("category"), Category);
		ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("name"), Name);
		ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("photoUrls"), PhotoUrls);
		ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("tags"), Tags);
		ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("status"), Status);

		return ParseSuccess;
	}
}
