/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ModelPrefixBaseModel.h"

namespace CppNamespace 
{

/*
 * ModelPrefixApiResponse
 *
 * Describes the result of uploading an image resource
 */
class PETSTORE_API ModelPrefixApiResponse : public Model
{
public:
    virtual ~ModelPrefixApiResponse() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<int32> Code;
	TOptional<FString> Type;
	TOptional<FString> Message;
};

}
