/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "ModelPrefixBaseModel.h"
#include "ModelPrefixCategory.h"
#include "ModelPrefixTag.h"

namespace CppNamespace 
{

/*
 * ModelPrefixPet
 *
 * A pet for sale in the pet store
 */
class PETSTORE_API ModelPrefixPet : public Model
{
public:
    virtual ~ModelPrefixPet() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<int64> Id;
	TOptional<ModelPrefixCategory> Category;
	FString Name;
	TArray<FString> PhotoUrls;
	TOptional<TArray<ModelPrefixTag>> Tags;
	enum class StatusEnum
	{
		Available,
		Pending,
		Sold,
  	};
	/* pet status in the store */
	TOptional<StatusEnum> Status;
};

}
