/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "ModelPrefixBaseModel.h"
#include "ModelPrefixStoreApi.h"

#include "ModelPrefixOrder.h"

namespace CppNamespace 
{

/* Delete purchase order by ID
 *
 * For valid response try integer IDs with value &lt; 1000. Anything above 1000 or nonintegers will generate API errors
*/
class PETSTORE_API ModelPrefixStoreApi::DeleteOrderRequest : public Request
{
public:
    virtual ~DeleteOrderRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* ID of the order that needs to be deleted */
	FString OrderId;
};

class PETSTORE_API ModelPrefixStoreApi::DeleteOrderResponse : public Response
{
public:
    virtual ~DeleteOrderResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    
};

/* Returns pet inventories by status
 *
 * Returns a map of status codes to quantities
*/
class PETSTORE_API ModelPrefixStoreApi::GetInventoryRequest : public Request
{
public:
    virtual ~GetInventoryRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest>& HttpRequest) const final;
	FString ComputePath() const final;
    
};

class PETSTORE_API ModelPrefixStoreApi::GetInventoryResponse : public Response
{
public:
    virtual ~GetInventoryResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    TMap<FString, int32> Content;
};

/* Find purchase order by ID
 *
 * For valid response try integer IDs with value &lt;&#x3D; 5 or &gt; 10. Other values will generated exceptions
*/
class PETSTORE_API ModelPrefixStoreApi::GetOrderByIdRequest : public Request
{
public:
    virtual ~GetOrderByIdRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* ID of pet that needs to be fetched */
	int64 OrderId;
};

class PETSTORE_API ModelPrefixStoreApi::GetOrderByIdResponse : public Response
{
public:
    virtual ~GetOrderByIdResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    ModelPrefixOrder Content;
};

/* Place an order for a pet
 *
 * 
*/
class PETSTORE_API ModelPrefixStoreApi::PlaceOrderRequest : public Request
{
public:
    virtual ~PlaceOrderRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* order placed for purchasing the pet */
	ModelPrefixOrder Body;
};

class PETSTORE_API ModelPrefixStoreApi::PlaceOrderResponse : public Response
{
public:
    virtual ~PlaceOrderResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    ModelPrefixOrder Content;
};

}
