/**
 * UE4GeneratorTester
 * test
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIPetApi.h"

#include "OpenAPIAllTypes.h"

namespace OpenAPI 
{

/* Update an existing pet

*/
class OPENAPI_API OpenAPIPetApi::UpdatePetRequest : public Request
{
public:
    virtual ~UpdatePetRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* Pet object that needs to be added to the store */
	OpenAPIAllTypes Body;
};

class OPENAPI_API OpenAPIPetApi::UpdatePetResponse : public Response
{
public:
    virtual ~UpdatePetResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    
};

}
