/**
 * UE4GeneratorTester
 * test
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI 
{

/*
 * OpenAPIAllTypes
 *
 * 
 */
class OPENAPI_API OpenAPIAllTypes : public Model
{
public:
    virtual ~OpenAPIAllTypes() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TSharedPtr<FJsonObject> Notype;
	int32 Int1 = 123456;
	int64 Int2 = 123456;
	int32 Int3 = 0;
	float Number1 = 123.456;
	float Number2 = 123.456;
	double Number3;
	FString String = TEXT("toto titi");
	TArray<uint8> StringByte;
	bool Boolean = true;
	FDateTime Date;
	FDateTime DateTime;
	FString Password = TEXT("true");
	enum class Enum1Enum
	{
		Enumvalue1,
		Enumvalue2,
		Enumvalue3,
  	};
	
	static FString EnumToString(const Enum1Enum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, Enum1Enum& EnumValue);
	TOptional<Enum1Enum> Enum1;
	TOptional<int32> Enum2;
};

}
