/**
 * UE4GeneratorTester
 * test
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI 
{

/*
 * OpenAPIEnumTypedef
 *
 * 
 */
class OPENAPI_API OpenAPIEnumTypedef : public Model
{
public:
    virtual ~OpenAPIEnumTypedef() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	enum class Values
	{
		_,
		__,
		A,
		AA,
		Enumvalue1,
		Enumvalue2,
		Enumvalue3,
  	};

	Values Value;
};

}
