/**
 * UE4GeneratorTester
 * test
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerModule.h"

IMPLEMENT_MODULE(SwaggerModule, Swagger);
DEFINE_LOG_CATEGORY(LogSwagger);

void SwaggerModule::StartupModule()
{
}

void SwaggerModule::ShutdownModule()
{
}

