/**
 * UE4GeneratorTester
 * test
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerAllTypes.h"

#include "SwaggerModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

inline FString ToString(const SwaggerAllTypes::Enum1Enum& Value)
{
	switch (Value)
	{
	case SwaggerAllTypes::Enum1Enum::Enumvalue1:
		return TEXT("enumvalue1");
	case SwaggerAllTypes::Enum1Enum::Enumvalue2:
		return TEXT("enumvalue2");
	case SwaggerAllTypes::Enum1Enum::Enumvalue3:
		return TEXT("enumvalue3");
	}

	UE_LOG(LogSwagger, Error, TEXT("Invalid SwaggerAllTypes::Enum1Enum Value (%d)"), (int)Value);	
	return TEXT("");
}

inline FStringFormatArg ToStringFormatArg(const SwaggerAllTypes::Enum1Enum& Value)
{
	return FStringFormatArg(ToString(Value));
}

inline void WriteJsonValue(JsonWriter& Writer, const SwaggerAllTypes::Enum1Enum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, SwaggerAllTypes::Enum1Enum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		static TMap<FString, SwaggerAllTypes::Enum1Enum> StringToEnum = {  };

		const auto Found = StringToEnum.Find(TmpValue);
		if(Found)
		{
			Value = *Found;
			return true;
		}
	}
	return false;
}

void SwaggerAllTypes::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("notype")); WriteJsonValue(Writer, Notype);
	Writer->WriteIdentifierPrefix(TEXT("int1")); WriteJsonValue(Writer, Int1);
	Writer->WriteIdentifierPrefix(TEXT("int2")); WriteJsonValue(Writer, Int2);
	Writer->WriteIdentifierPrefix(TEXT("int3")); WriteJsonValue(Writer, Int3);
	Writer->WriteIdentifierPrefix(TEXT("number1")); WriteJsonValue(Writer, Number1);
	Writer->WriteIdentifierPrefix(TEXT("number2")); WriteJsonValue(Writer, Number2);
	Writer->WriteIdentifierPrefix(TEXT("number3")); WriteJsonValue(Writer, Number3);
	Writer->WriteIdentifierPrefix(TEXT("string")); WriteJsonValue(Writer, String);
	Writer->WriteIdentifierPrefix(TEXT("string_byte")); WriteJsonValue(Writer, StringByte);
	Writer->WriteIdentifierPrefix(TEXT("string_binary")); WriteJsonValue(Writer, StringBinary);
	Writer->WriteIdentifierPrefix(TEXT("boolean")); WriteJsonValue(Writer, Boolean);
	Writer->WriteIdentifierPrefix(TEXT("date")); WriteJsonValue(Writer, Date);
	Writer->WriteIdentifierPrefix(TEXT("date_time")); WriteJsonValue(Writer, DateTime);
	Writer->WriteIdentifierPrefix(TEXT("password")); WriteJsonValue(Writer, Password);
	if (Enum1.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("enum1")); WriteJsonValue(Writer, Enum1.GetValue());	
	}
	if (Enum2.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("enum2")); WriteJsonValue(Writer, Enum2.GetValue());	
	}
	Writer->WriteObjectEnd();
}

bool SwaggerAllTypes::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("notype"), Notype);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("int1"), Int1);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("int2"), Int2);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("int3"), Int3);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("number1"), Number1);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("number2"), Number2);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("number3"), Number3);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("string"), String);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("string_byte"), StringByte);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("string_binary"), StringBinary);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("boolean"), Boolean);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("date"), Date);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("date_time"), DateTime);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("password"), Password);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("enum1"), Enum1);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("enum2"), Enum2);

	return ParseSuccess;
}
}
