/**
 * UE4GeneratorTester
 * test
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"

namespace Swagger 
{

/*
 * SwaggerAllTypes
 *
 * 
 */
class SWAGGER_API SwaggerAllTypes : public Model
{
public:
    virtual ~SwaggerAllTypes() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	TSharedPtr<FJsonObject> Notype;
	int32 Int1 = 123456;
	int64 Int2 = 123456;
	int32 Int3 = 0;
	float Number1 = 123.456;
	float Number2 = 123.456;
	double Number3 = 0.0;
	FString String = TEXT("toto titi");
	TArray<uint8> StringByte;
	TArray<uint8> StringBinary;
	bool Boolean = true;
	FDateTime Date = FDateTime(0);
	FDateTime DateTime = FDateTime(0);
	FString Password = TEXT("true");
	enum class Enum1Enum
	{
		Enumvalue1,
		Enumvalue2,
		Enumvalue3,
  	};
	TOptional<Enum1Enum> Enum1;
	TOptional<int32> Enum2;
};

}
